### ISSUE TITLE
Populating the data

### ISSUE THREAD

**Issue by skprasadu** [Doist/bitmapist#15]
How do I populate data into Bitmapist so that I can play with your queries..

Do you have a utility to populate domain/ application specific data and run bunch of the queries as you had put and gauge, how fast it works..

That will be helpful.

Krishna

**Comment by imankulov** [comment]
Hello @skprasadu 

`mark_event` provides an optional `now` argument which you can use to import data from your source. To speed up the process, you can also use Redis pipelines. With pipelines you provide a pipeline object as a system argument, and set `use_pipeline=False` as an argument value (yes, `use_pipeline=False` is not a typo, but rather a horribly misleading name for the variable).

Here is a trivial example

```python
import datetime
import bitmapist

r = bitmapist.get_redis()
pipe = r.pipeline()
uid = 1
for day in range(365):
    dt = datetime.datetime(2015, 1, 1) + datetime.timedelta(day)
    bitmapist.mark_event('foo', uid, now=dt, system=pipe, use_pipeline=False)

pipe.execute()
```
