### ISSUE TITLE
Storing extra data

### ISSUE THREAD

**Issue by altunyurt** [Doist/bitmapist#19]
Is there a more efficient way to store extra data for scenarios like 'user x replied question y correctly|falsely in z seconds'?

I think implementations such as 
```
mark_event("question:y:x:1/0', z)
```
would be neither effective nor useful for queries.

Some examples on this would be very helpful.

**Comment by imankulov** [comment]
I'm not sure bitmapist is right tool for that. It's core feature is to keep track events with time, and in fact it's a quite tiny convenience wrapper around redis bit commands. In your case I would resort to simple bit operations on [strings](http://redis.io/commands#string) with Redis. Not sure if it's still relevant for you though :)
