### ISSUE TITLE
A Compliment and Quandary

### ISSUE THREAD

**Issue by jpotts18** [Doist/bitmapist#22]
A co-worker of mine showed me this library. I think this is an excellent use of bitmaps! I think I see another interesting extension of this bitmapist library and I wanted to get your feedback. 

I work for a company that needs an almost real-time recommendation engine. I started thinking about the application of bitmaps into [collaborative filtering](https://en.wikipedia.org/wiki/Collaborative_filtering). Basically in collaborative filtering you need a matrix that is comprised of `[users * products]`

![](https://upload.wikimedia.org/wikipedia/commons/5/52/Collaborative_filtering.gif)

The idea in this instance would basically be to have a `SETBIT users:20160614:1 [product_id] 1` for each user that is representative of what product they like. You would also need to have a `SETBIT products:20160614:1 [user_id] 1` this would have an index into each user.  

Wait I think I see a problem with this. How would we represent an empty space in the matrix? A cooccurrence matrix has 3 states (Like, Dislike, Unknown). I guess you could probably combine them in some way or maybe my bit operations are rusty. 

The main benefits in this would be the storage savings that this could have. When I did a quick calculation based on traffic a site like ours would see in a day it would be about (700 products * 300k users) 26.25MB

I understand that you are probably not interested in having this be part of this repo. I'd mainly like your feedback and advice. Thanks!

**Comment by imankulov** [comment]
Hi @jpotts18. To be frank, I'm not sure I follow you completely, and not sure how bitmapist can be helpful in your case. Nonetheless, I agree that the memory can become eventually a concern. In this case, providing that bitmapist machines most likely will be underloaded by CPU, we found that [zram](https://en.wikipedia.org/wiki/Zram) usage can be very helpful. In our scenario switching to zram helped us to fit 6x more data in the same amount of RAM. Hope this helps!
