### ISSUE TITLE
Total Events

### ISSUE THREAD

**Issue by frankV** [Doist/bitmapist#25]
Is there currently way to determine the total number of occurrences for a given event?

Would there be a way to achieve this within scope's of `Weeks|Months|YearsEvents()`

**Comment by imankulov** [comment]
Unfortunately, there's no way bitmapist can give the answer of that type of questions. 

What it can do is to give a response of the type `On <that period> event X never happened to user Y` VS `On <that period> event X happened to user Y at least once`.

**Comment by frankV** [comment]
Thanks, @imankulov
