### ISSUE TITLE
Behavior of NOT operator on empty bitmaps

### ISSUE THREAD

**Issue by rkenmi** [Doist/bitmapist#28]
Hello,

I noticed a little quirk on NOT operators for empty bitmaps.

Say for example that a bitmap represents a byte of 0's (0000 0000).
When this byte is negated, it _should_ give back (1111 1111) or a value of 255.
Instead, I am getting back another 0.

On non-empty bitmaps, the NOT operator seems to work fine, only up to the highest flagged bit.

Currently, if some bitmaps are empty, I have to manually flag/mark an event with a large dummy ID in order to make the NOT operator work. 

Are there better ways of accomplishing this?

**Comment by imankulov** [comment]
Hi Rick,

Yes, that's the limitation of bitmapist. The workaround is to avoid using NOT operator in your computations. It's not always possible, but in some cases there is an equivalent which works. For example, `a AND NOT b` is an equivalent for `a XOR b AND a`. 

* [code snippet](https://gist.github.com/imankulov/1ea14fb895f5eacdae968683ea219075)
* [wolframalpha](https://www.wolframalpha.com/input/?i=a+AND+NOT+b)
