### ISSUE TITLE
Version 3.100 available on PyPI, but not in Github releases

### ISSUE THREAD

**Issue by rohitpaulk** [Doist/bitmapist#29]
Available at https://pypi.python.org/pypi/bitmapist#downloads, but isn't tagged in the GitHub repo. 

@imankulov Just to confirm, tagging the current master with `3.100` should do, yes?

**Comment by imankulov** [comment]
@rohitpaulk, thanks for flagging. Pushed the tag to GitHub (was tagged locally, but I forgot to make `git push --tags`)
