### ISSUE TITLE
UniqueEvents query is very slow 

### ISSUE THREAD

**Issue by altunyurt** [Doist/bitmapist#30]
I'm trying to store the user likes in redis, using bitmaps to store _this question_id is liked by these users_. But apparently, unique events is somehow way slow for the operation. 

    In [1]: from bitmapist import mark_unique
    In [2]: mark_unique("question_likes:1234", 567463)
    In [3]: mark_unique("question_likes:1234", 5637363)
    In [4]: mark_unique("question_likes:1234", 7363)
    In [5]: mark_unique("question_likes:1234", 731263)
    In [6]: mark_unique("question_likes:1234", 731263)
    In [7]: from bitmapist import UniqueEvents
    In [38]: %cpaste
    Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
    :uids = UniqueEvents('question_likes:1234').get_uuids()
    :t = time()
    :for i in uids:
    :    print i
    :print "elapsed time:", time() - t
    :--
    7363
    567463
    731263
    5637363
    elapsed time: 14.1893291473

I'm running the latest bitmapist on Redis server v=4.0.9 on linux mint. 

Her is th debug object output for the key: 

    127.0.0.1:6379> DEBUG OBJECT trackist_question_likes:1234_u
    Value at:0x7f979b6a51e0 refcount:1 encoding:raw serializedlength:8036 lru:12900027 lru_seconds_idle:252

**Comment by imankulov** [comment]
Thanks for the catch, @altunyurt!

The issue is found, fixed and deployed as [bitmapist 3.101](https://pypi.python.org/pypi/bitmapist/3.101) 🎉
